// Grinrex IoT — demo Alerts & event log. The whole alert queue with acknowledgement, plus a
// searchable, source-filtered view of every event the loop has recorded.
import { AlertTriangle, BellOff, BellRing, CheckCheck, Filter, Info, RotateCcw, Search, ShieldAlert, Timer } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { DemoLayout } from "./DemoLayout";
import { useGarden } from "./GardenContext";
import { demoLink } from "./sections";
import { formatSimClock, logCapFor } from "./simulation";

type FilterKey = "all" | "critical" | "warn" | "calm" | "acked";

const filters: { key: FilterKey; label: string }[] = [
  { key: "all", label: "All open" },
  { key: "critical", label: "Critical" },
  { key: "warn", label: "Warning" },
  { key: "calm", label: "Info & ok" },
  { key: "acked", label: "Acknowledged" },
];

function alertIcon(kind: string) {
  switch (kind) {
    case "critical":
      return <ShieldAlert size={15} className="shrink-0 text-[#ff6b57]" />;
    case "warn":
      return <AlertTriangle size={15} className="shrink-0 text-[#d9a35c]" />;
    case "ok":
      return <CheckCheck size={15} className="shrink-0 text-[#b8f15a]" />;
    default:
      return <Info size={15} className="shrink-0 text-[#8fd3b4]" />;
  }
}

export default function AlertsPage() {
  useDemoMeta("/alerts");
  const { state, actions } = useGarden();
  const [filter, setFilter] = useState<FilterKey>("all");
  const [query, setQuery] = useState("");
  const [source, setSource] = useState<string>("All");

  const visibleAlerts = useMemo(() => {
    return state.alerts.filter(alert => {
      if (filter === "acked") return alert.acked;
      if (alert.acked) return false;
      if (filter === "all") return true;
      if (filter === "calm") return alert.kind === "info" || alert.kind === "ok";
      return alert.kind === filter;
    });
  }, [state.alerts, filter]);

  const sources = useMemo(() => ["All", ...Array.from(new Set(state.log.map(entry => entry.source)))], [state.log]);

  const visibleLog = useMemo(() => {
    const needle = query.trim().toLowerCase();
    return state.log.filter(entry => {
      if (source !== "All" && entry.source !== source) return false;
      if (!needle) return true;
      return entry.message.toLowerCase().includes(needle) || entry.source.toLowerCase().includes(needle);
    });
  }, [state.log, query, source]);

  const open = state.alerts.filter(alert => !alert.acked);
  const criticalOpen = open.filter(alert => alert.kind === "critical");
  const warnOpen = open.filter(alert => alert.kind === "warn");
  const held = state.log.filter(entry => entry.source === "Alerts");
  const bySource = useMemo(() => {
    const counts = new Map<string, number>();
    for (const entry of state.log) counts.set(entry.source, (counts.get(entry.source) ?? 0) + 1);
    return Array.from(counts.entries()).sort((a, b) => b[1] - a[1]);
  }, [state.log]);
  const maxSource = Math.max(1, ...bySource.map(([, count]) => count));

  const quietNow = state.settings.respectQuietHours;

  return (
    <DemoLayout>
      <div className="flex flex-col gap-8">
        <DemoPageHeader
          path="/alerts"
          title="The thing that tells you"
          accent="something changed."
          copy="Alerts are generated by the same rules that drive the valves, so they can never contradict the garden. Non-critical advisories obey quiet hours and the notification profile; safety alerts cannot be muted."
          aside={
            <>
              <StatTile label="Open alerts" value={open.length} sub={`${state.alerts.length} in the queue`} tone={open.length ? "text-[#ffd49c]" : "text-[#b8f15a]"} icon={<BellRing size={15} className="text-[#d9a35c]" />} />
              <StatTile label="Critical" value={criticalOpen.length} sub="never muted" tone={criticalOpen.length ? "text-[#ff9c8c]" : "text-[#efffd3]"} icon={<ShieldAlert size={15} className="text-[#ff6b57]" />} />
              <StatTile label="Events held" value={state.log.length} sub={`buffer of ${logCapFor(state.settings.retentionDays)}`} icon={<Timer size={15} className="text-[#8fae93]" />} />
            </>
          }
        />

        <div className="grid gap-4 lg:grid-cols-[1fr_1.15fr]">
          {/* alert queue */}
          <div className="demo-panel p-5">
            <DemoSectionTitle
              title="Alert queue"
              action={
                <button className="demo-chip" onClick={actions.ackAllAlerts} aria-label="Acknowledge all alerts" disabled={open.length === 0}>
                  <CheckCheck size={12} /> Ack all ({open.length})
                </button>
              }
            />
            <div className="mb-4 flex flex-wrap gap-1.5">
              {filters.map(item => (
                <button key={item.key} className="demo-chip" data-on={filter === item.key} onClick={() => setFilter(item.key)} aria-label={`Filter alerts: ${item.label}`}>
                  {item.label}
                </button>
              ))}
            </div>

            {visibleAlerts.length === 0 ? (
              <div className="rounded-xl border border-dashed border-white/12 bg-white/[.02] p-6 text-center">
                <p className="text-sm text-[#8fae93]">Nothing in this view. The loop only raises what it can measure.</p>
                <p className="interface mt-2 text-[.56rem] font-extrabold uppercase tracking-[.14em] text-[#7e9a80]">
                  {warnOpen.length} warning · {criticalOpen.length} critical still open
                </p>
                <Link href={demoLink("/")} className="interface mt-4 inline-block text-[.6rem] font-extrabold uppercase tracking-[.1em] text-[#b8f15a] hover:text-[#d0ff88]">
                  Back to overview →
                </Link>
              </div>
            ) : (
              <ul className="space-y-2.5">
                {visibleAlerts.map(alert => (
                  <li key={alert.id} className="alert-item rounded-lg bg-white/[.035] p-3.5" data-kind={alert.kind}>
                    <div className="flex items-center gap-2.5">
                      {alertIcon(alert.kind)}
                      <span className="text-sm font-bold text-[#effadf]">{alert.title}</span>
                      <span className="interface ml-auto shrink-0 text-[.56rem] font-extrabold text-[#8fae93]">{formatSimClock(alert.simMin, state.settings.clock24h)}</span>
                    </div>
                    <p className="mt-1.5 text-xs leading-5 text-[#a9c1a2]">{alert.detail}</p>
                    <div className="mt-2.5 flex items-center gap-2">
                      {alert.acked ? (
                        <span className="valve-badge valve-open">Acknowledged</span>
                      ) : (
                        <button className="demo-chip" onClick={() => actions.ackAlert(alert.id)} aria-label={`Acknowledge ${alert.title}`}>
                          <CheckCheck size={12} /> Acknowledge
                        </button>
                      )}
                      <Link href={demoLink("/rules")} className="interface text-[.56rem] font-extrabold uppercase tracking-[.1em] text-[#8fae93] hover:text-[#b8f15a]">
                        Tune the rule →
                      </Link>
                    </div>
                  </li>
                ))}
              </ul>
            )}

            {quietNow && (
              <p className="mt-4 flex items-start gap-2 rounded-xl border border-[#d9a35c]/25 bg-[#332b1c] p-3 text-xs leading-5 text-[#d6c8aa]">
                <BellOff size={13} className="mt-0.5 shrink-0" />
                Quiet hours are on ({formatSimClock(state.settings.quietStartMin, state.settings.clock24h)}–{formatSimClock(state.settings.quietEndMin, state.settings.clock24h)}
                ): non-critical advisories are written to the log instead of the queue.{" "}
                <Link href={demoLink("/settings")} className="text-[#f0d5a4] underline decoration-dotted">
                  Settings
                </Link>
              </p>
            )}
          </div>

          {/* event log */}
          <div className="demo-panel p-5">
            <DemoSectionTitle title="Event log" note={`${visibleLog.length} of ${state.log.length} events`} />
            <div className="mb-3 flex flex-wrap items-center gap-2">
              <label className="relative min-w-[12rem] flex-1">
                <Search size={13} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[#7e9a80]" />
                <input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search the log…" className="demo-field w-full pl-9" aria-label="Search the event log" />
              </label>
              <button
                className="demo-chip"
                onClick={() => {
                  setQuery("");
                  setSource("All");
                }}
                aria-label="Clear log filters"
              >
                <RotateCcw size={12} /> Clear
              </button>
            </div>
            <div className="mb-3 flex flex-wrap gap-1.5">
              {sources.slice(0, 9).map(name => (
                <button key={name} className="demo-chip" data-on={source === name} onClick={() => setSource(name)} aria-label={`Filter by source ${name}`}>
                  <Filter size={11} /> {name}
                </button>
              ))}
            </div>
            <ul className="demo-scroll max-h-[26rem] space-y-2 overflow-y-auto pr-1">
              {visibleLog.length === 0 ? (
                <li className="rounded-lg border border-dashed border-white/12 p-4 text-center text-xs text-[#8fae93]">No events match this filter.</li>
              ) : (
                visibleLog.slice(0, 90).map(entry => (
                  <li key={entry.id} className="alert-item rounded-lg bg-white/[.03] px-3 py-2" data-kind={entry.kind}>
                    <div className="flex items-center gap-2">
                      {alertIcon(entry.kind)}
                      <span className="interface text-[.56rem] font-extrabold uppercase tracking-[.1em] text-[#d9a35c]">{entry.source}</span>
                      <span className="interface ml-auto text-[.56rem] font-extrabold text-[#8fae93]">{formatSimClock(entry.simMin, state.settings.clock24h)}</span>
                    </div>
                    <p className="mt-1 text-xs leading-5 text-[#b8cbb0]">{entry.message}</p>
                  </li>
                ))
              )}
            </ul>
          </div>
        </div>

        {/* distribution + held advisories */}
        <div className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]">
          <div className="demo-panel p-5">
            <DemoSectionTitle title="Events by source" note="which part of the system is talking" />
            <div className="space-y-2.5">
              {bySource.map(([name, count]) => (
                <div key={name} className="flex items-center gap-4">
                  <span className="interface w-28 shrink-0 truncate text-[.62rem] font-extrabold uppercase tracking-[.08em] text-[#c9dcbf]">{name}</span>
                  <div className="h-2.5 flex-1 overflow-hidden rounded-full bg-white/[.06]">
                    <div
                      className="h-full rounded-full bg-gradient-to-r from-[#8fd3b4] to-[#b8f15a] transition-all duration-700"
                      style={{
                        width: `${Math.round((count / maxSource) * 100)}%`,
                      }}
                    />
                  </div>
                  <span className="interface w-10 shrink-0 text-right text-xs font-extrabold text-[#efffd3]">{count}</span>
                </div>
              ))}
            </div>
          </div>
          <div className="demo-panel p-5">
            <DemoSectionTitle title="Held & muted advisories" note="quiet hours and notification profile" />
            {held.length === 0 ? (
              <p className="text-sm text-[#8fae93]">Nothing has been held. Warnings suppressed by quiet hours or the notification profile land here as log lines instead of pings.</p>
            ) : (
              <ul className="space-y-2">
                {held.slice(0, 8).map(entry => (
                  <li key={entry.id} className="rounded-lg bg-white/[.03] px-3 py-2">
                    <div className="interface text-[.56rem] font-extrabold uppercase tracking-[.1em] text-[#8fae93]">
                      {formatSimClock(entry.simMin, state.settings.clock24h)} · {entry.kind}
                    </div>
                    <p className="mt-1 text-xs leading-5 text-[#b8cbb0]">{entry.message}</p>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>
      </div>
    </DemoLayout>
  );
}
import { DemoPageHeader, DemoSectionTitle, StatTile, useDemoMeta } from "./ui";
