// Grinrex IoT — live demo simulation engine.
// A deterministic, tick-driven model of a real garden loop: weather drives evaporation,
// soil moisture decays, the rule engine opens valves, and the tank drains — with safety
// cutoffs, eco mode, rain events, and a full event/alert log. Purely in-browser; no backend.
// Every page under /demo reads from the same live GardenProvider, so changes made on one
// page are visible on all others.
//
// The engine models the whole product surface, not only irrigation: device health and
// firmware, schedule windows and guardrails, fertilizer dosing, the growth/pest camera,
// generated garden tasks, and rainwater harvesting into the tank.

export type SimWeather = {
  temp: number; // °C
  humidity: number; // %
  light: number; // 0-100 (daylight strength)
  wind: number; // km/h
  raining: boolean;
  rainIntensity: number; // 0-1
  rainMmPerHour: number; // rainfall rate
};

export type ZoneState = {
  id: string;
  name: string;
  plant: string;
  moisture: number; // %
  target: number; // % — desired soil moisture
  temp: number; // °C at zone
  light: number; // 0-100
  valveOpen: boolean;
  auto: boolean;
  pausedByRain: boolean;
  lastWateredSimMin: number | null;
  consumedToday: number; // liters
  consumedTotal: number; // liters
  cycleStartSimMin: number | null; // start of the running watering cycle
  wantsWater: boolean; // the soil says "water me" right now
  holdReason: string | null; // why the engine is not opening the valve (if it isn't)
  fertApplied: number; // ml injected during the current/last cycle
};

export type TankState = {
  level: number; // liters
  capacity: number; // liters
  rainShare: number; // liters currently from rainwater
  muniShare: number; // liters from municipal
  lowThreshold: number; // liters
  criticalThreshold: number; // liters
};

export type AlertKind = "info" | "warn" | "critical" | "ok";

export type LogEntry = {
  id: number;
  simMin: number;
  realTime: number;
  kind: AlertKind;
  source: string;
  message: string;
};

export type AlertEntry = {
  id: number;
  kind: AlertKind;
  title: string;
  detail: string;
  simMin: number;
  acked: boolean;
};

// --- devices ----------------------------------------------------------------
export type DeviceKind = "controller" | "pump" | "camera" | "sensor" | "valve";
export type DevicePower = "mains" | "battery" | "solar";

export type DeviceState = {
  id: string;
  name: string;
  kind: DeviceKind;
  model: string;
  zoneId?: string;
  powered: DevicePower;
  battery: number | null; // % — null when mains powered
  rssi: number; // dBm
  firmware: string;
  pendingFirmware: string | null; // queued OTA update
  online: boolean;
  offlineUntilSimMin: number | null; // reboot / OTA window
  lastSeenSimMin: number;
  fault: string | null;
};

// --- rules & schedules ------------------------------------------------------
export type ScheduleWindow = {
  id: string;
  label: string;
  startMin: number; // minutes since midnight
  endMin: number;
  enabled: boolean;
};

export type RulesState = {
  windows: ScheduleWindow[];
  maxCycleMin: number; // hard bound on a single watering cycle
  rainSkipMin: number; // hold auto watering this long after rain ends
  freezeProtectC: number; // no irrigation below this temperature
  dryRun: boolean; // preview decisions without driving actuators
};

// --- fertilizer ---------------------------------------------------------------
export type FertChannel = {
  id: string;
  name: string;
  zoneId: string;
  doseMl: number; // per watering cycle
  reservoirMl: number; // stock left
  enabled: boolean;
  todayMl: number;
  totalMl: number;
  lastDosedSimMin: number | null;
};

export type FertilizerState = {
  enabled: boolean;
  lockout: boolean; // safety lockout — dosing blocked even if enabled
  channels: FertChannel[];
};

// --- camera: growth time-lapse + advisory pest insight -----------------------
export type PestStatus = "needs-review" | "confirmed" | "dismissed";

export type PestSignature = {
  name: string;
  confidence: number; // 0-1
  status: PestStatus;
};

export type Snapshot = {
  id: number;
  simMin: number;
  zoneId: string;
  zoneName: string;
  moisture: number;
  light: number;
  growthIndex: number;
  pest: PestSignature | null;
};

export type CameraState = {
  enabled: boolean;
  intervalMin: number; // capture cadence in simulated minutes
  lastCaptureSimMin: number | null;
  captures: number;
  storagePct: number;
  growthIndex: number; // 0-100
  healthScore: number; // 0-100
  seq: number;
  snapshots: Snapshot[];
};

// --- garden assistant tasks ---------------------------------------------------
export type TaskKind = "care" | "check" | "harvest" | "prune" | "note";

export type GardenTask = {
  id: string;
  title: string;
  detail: string;
  kind: TaskKind;
  dueSimMin: number;
  done: boolean;
  auto: boolean; // generated by the engine rather than the gardener
  zoneId?: string;
};

export type GardenNote = { id: number; simMin: number; text: string };

// --- rainwater harvesting -----------------------------------------------------
export type HarvestDay = {
  day: string;
  mm: number;
  liters: number;
  overflow: boolean;
};

export type HarvestState = {
  catchmentM2: number; // roof / balcony catchment area
  efficiency: number; // 0-1 — first-flush and gutter losses
  routedToTank: boolean; // send harvested water to the storage tank
  collectedTodayL: number;
  collectedTotalL: number;
  rainMmToday: number;
  overflowCount: number;
  lastOverflowSimMin: number | null;
  daily: HarvestDay[];
};

// --- site settings ------------------------------------------------------------
export type UnitSystem = "metric" | "imperial";

export type SiteSettings = {
  gardenName: string;
  location: string;
  units: UnitSystem;
  clock24h: boolean;
  respectQuietHours: boolean;
  quietStartMin: number;
  quietEndMin: number;
  notifyCritical: boolean;
  notifyWarn: boolean;
  dailyDigest: boolean;
  retentionDays: number;
  offlineFallback: "local" | "safe-stop";
};

export type SimState = {
  running: boolean;
  simMin: number; // simulated minutes since demo start
  speed: number; // sim minutes per real second
  eco: boolean;
  autoGlobal: boolean;
  emergencyStop: boolean;
  weather: SimWeather;
  zones: ZoneState[];
  tank: TankState;
  log: LogEntry[];
  alerts: AlertEntry[];
  waterToday: number; // liters
  waterYesterday: number; // liters
  rainwaterToday: number; // liters
  estimatedSavingsL: number; // liters saved by rain-first logic
  history: SimHistoryPoint[];
  logSeq: number;
  alertSeq: number;
  devices: DeviceState[];
  rules: RulesState;
  fertilizer: FertilizerState;
  camera: CameraState;
  tasks: GardenTask[];
  taskSeq: number;
  notes: GardenNote[];
  noteSeq: number;
  harvest: HarvestState;
  settings: SiteSettings;
  lastRainEndSimMin: number | null;
};

export type SimHistoryPoint = {
  t: number; // simMin
  temp: number;
  humidity: number;
  light: number;
  wind: number;
  rain: number; // mm/h
  avgMoisture: number;
  tankLevel: number;
  flowRate: number; // l/min
  growthIndex: number;
};

// ---- deterministic PRNG (mulberry32) -------------------------------------
function mulberry32(seed: number) {
  let a = seed >>> 0;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const rand = mulberry32(20260831);
const clamp = (v: number, min: number, max: number) => Math.min(max, Math.max(min, v));
const round1 = (v: number) => Math.round(v * 10) / 10;

const DAY_MIN = 24 * 60;
const TICK_MIN = 4; // sim minutes per tick

export const zoneDefaults = [
  {
    id: "z1",
    name: "Balcony greens",
    plant: "Herbs & salad greens",
    moisture: 46,
    target: 42,
  },
  { id: "z2", name: "Tomato bed", plant: "Tomatoes", moisture: 34, target: 38 },
  {
    id: "z3",
    name: "Vertical wall A",
    plant: "Leafy greens",
    moisture: 29,
    target: 36,
  },
  {
    id: "z4",
    name: "Vertical wall B",
    plant: "Strawberries",
    moisture: 40,
    target: 34,
  },
] as const;

export const soilDeviceId = (zoneId: string) => `soil-${zoneId}`;
export const valveDeviceId = (zoneId: string) => `valve-${zoneId}`;

const pestLibrary = ["Two-spotted mite", "Aphid colony", "Powdery mildew", "Whitefly", "Leaf miner"] as const;

function buildDevices(zones: ZoneState[]): DeviceState[] {
  const shared = {
    firmware: "1.2.0",
    online: true,
    offlineUntilSimMin: null,
    lastSeenSimMin: 6 * 60,
    fault: null,
    pendingFirmware: null,
  } as const;
  const base: DeviceState[] = [
    {
      id: "edge-01",
      name: "Edge controller",
      kind: "controller",
      model: "ESP32-S3 · Grinrex Core",
      powered: "mains",
      battery: null,
      rssi: -52,
      ...shared,
      firmware: "1.4.2",
      pendingFirmware: "1.4.3",
    },
    {
      id: "pump-01",
      name: "Pump & valve manifold",
      kind: "pump",
      model: "24 V diaphragm · 4-channel block",
      powered: "mains",
      battery: null,
      rssi: -58,
      ...shared,
      firmware: "1.4.0",
      pendingFirmware: null,
    },
    {
      id: "cam-01",
      name: "Garden camera",
      kind: "camera",
      model: "ESP32-CAM · interval rig",
      powered: "solar",
      battery: 71,
      rssi: -69,
      ...shared,
      firmware: "0.9.7",
      pendingFirmware: "1.0.1",
    },
    {
      id: "tank-01",
      name: "Tank level & flow metering",
      kind: "sensor",
      model: "US-100 ultrasonic · YF-S201 flow",
      powered: "mains",
      battery: null,
      rssi: -61,
      ...shared,
      firmware: "1.2.4",
      pendingFirmware: null,
    },
    {
      id: "met-01",
      name: "Weather mast",
      kind: "sensor",
      model: "BME280 · BH1750 · rain gauge · anemometer",
      powered: "solar",
      battery: 84,
      rssi: -66,
      ...shared,
      firmware: "1.2.0",
      pendingFirmware: null,
    },
  ];

  const perZone: DeviceState[] = zones.flatMap(zone => [
    {
      id: soilDeviceId(zone.id),
      name: `${zone.name} — soil node`,
      kind: "sensor" as const,
      model: "Capacitive soil · DS18B20 soil temp",
      zoneId: zone.id,
      powered: "battery" as const,
      battery: 46 + Math.round(rand() * 50),
      rssi: -58 - Math.round(rand() * 22),
      firmware: "1.2.0",
      pendingFirmware: null,
      online: true,
      offlineUntilSimMin: null,
      lastSeenSimMin: 6 * 60,
      fault: null,
    },
    {
      id: valveDeviceId(zone.id),
      name: `${zone.name} — valve`,
      kind: "valve" as const,
      model: "Normally-closed solenoid · 24 V",
      zoneId: zone.id,
      powered: "mains" as const,
      battery: null,
      rssi: -60 - Math.round(rand() * 12),
      firmware: "1.1.8",
      pendingFirmware: null,
      online: true,
      offlineUntilSimMin: null,
      lastSeenSimMin: 6 * 60,
      fault: null,
    },
  ]);

  return [...base, ...perZone];
}

function buildHarvest(): HarvestState {
  const rand2 = mulberry32(4711);
  const daily: HarvestDay[] = [];
  for (let i = 13; i >= 0; i--) {
    const wet = rand2();
    const mm = wet > 0.62 ? Math.round(wet * 26 * 10) / 10 : Math.round(rand2() * 22) / 10;
    const liters = Math.round(mm * 12 * 0.62 * 10) / 10;
    daily.push({
      day: i === 0 ? "Today" : `D-${i}`,
      mm,
      liters,
      overflow: liters > 90,
    });
  }
  return {
    catchmentM2: 12,
    efficiency: 0.62,
    routedToTank: true,
    collectedTodayL: 0,
    collectedTotalL: 1684,
    rainMmToday: 0,
    overflowCount: 2,
    lastOverflowSimMin: null,
    daily,
  };
}

function buildTasks(simMin: number): GardenTask[] {
  return [
    {
      id: "t1",
      title: "Flush drip lines on Vertical wall A",
      detail: "Last flush was 9 days ago; emitters on the top level run smaller.",
      kind: "check",
      dueSimMin: simMin + 180,
      done: false,
      auto: false,
      zoneId: "z3",
    },
    {
      id: "t2",
      title: "Harvest basil before it bolts",
      detail: "Balcony greens — cut above the second node to keep the plant bushy.",
      kind: "harvest",
      dueSimMin: simMin + 320,
      done: false,
      auto: false,
      zoneId: "z1",
    },
    {
      id: "t3",
      title: "Top up rain barrel before the forecast break",
      detail: "Forecast dry spell from day 3; barrel is at 76%.",
      kind: "care",
      dueSimMin: simMin + 420,
      done: false,
      auto: false,
    },
    {
      id: "t4",
      title: "Pinch tomato side shoots",
      detail: "Single-leader training on the main truss.",
      kind: "prune",
      dueSimMin: simMin + 700,
      done: false,
      auto: false,
      zoneId: "z2",
    },
    {
      id: "t5",
      title: "Review first automatic week",
      detail: "Check cycle counts and stop-moisture overshoot before widening autonomy.",
      kind: "note",
      dueSimMin: simMin + 1200,
      done: false,
      auto: false,
    },
  ];
}

export function initialSimState(): SimState {
  const zones: ZoneState[] = zoneDefaults.map(z => ({
    ...z,
    temp: 21.5,
    light: 8,
    valveOpen: false,
    auto: true,
    pausedByRain: false,
    lastWateredSimMin: null,
    consumedToday: 0,
    consumedTotal: round1(rand() * 60 + 30),
    cycleStartSimMin: null,
    wantsWater: false,
    holdReason: null,
    fertApplied: 0,
  }));

  const startMin = 6 * 60;

  return {
    running: true,
    simMin: startMin, // start at 06:00 simulated time
    speed: 6, // sim minutes per real second
    eco: true,
    autoGlobal: true,
    emergencyStop: false,
    weather: {
      temp: 21.4,
      humidity: 74,
      light: 8,
      wind: 6.2,
      raining: false,
      rainIntensity: 0,
      rainMmPerHour: 0,
    },
    zones,
    tank: {
      level: 168,
      capacity: 220,
      rainShare: 96,
      muniShare: 72,
      lowThreshold: 55,
      criticalThreshold: 30,
    },
    log: [],
    alerts: [],
    waterToday: 0,
    waterYesterday: 41.6,
    rainwaterToday: 0,
    estimatedSavingsL: 183,
    history: [],
    logSeq: 1,
    alertSeq: 1,
    devices: buildDevices(zones),
    rules: {
      windows: [
        {
          id: "w1",
          label: "Morning window",
          startMin: 5 * 60 + 30,
          endMin: 9 * 60,
          enabled: true,
        },
        {
          id: "w2",
          label: "Evening window",
          startMin: 17 * 60 + 30,
          endMin: 21 * 60,
          enabled: true,
        },
      ],
      maxCycleMin: 12,
      rainSkipMin: 45,
      freezeProtectC: 3,
      dryRun: false,
    },
    fertilizer: {
      enabled: true,
      lockout: false,
      channels: [
        {
          id: "f1",
          name: "Grow mix A · nitrogen",
          zoneId: "z2",
          doseMl: 24,
          reservoirMl: 940,
          enabled: true,
          todayMl: 0,
          totalMl: 1260,
          lastDosedSimMin: null,
        },
        {
          id: "f2",
          name: "Leaf mix B · balanced",
          zoneId: "z1",
          doseMl: 16,
          reservoirMl: 610,
          enabled: true,
          todayMl: 0,
          totalMl: 742,
          lastDosedSimMin: null,
        },
        {
          id: "f3",
          name: "Berry mix C · low N",
          zoneId: "z4",
          doseMl: 12,
          reservoirMl: 288,
          enabled: false,
          todayMl: 0,
          totalMl: 190,
          lastDosedSimMin: null,
        },
      ],
    },
    camera: {
      enabled: true,
      intervalMin: 90,
      lastCaptureSimMin: startMin - 40,
      captures: 3,
      storagePct: 41,
      growthIndex: 64,
      healthScore: 78,
      seq: 4,
      snapshots: [
        {
          id: 1,
          simMin: startMin - 420,
          zoneId: "z1",
          zoneName: "Balcony greens",
          moisture: 44,
          light: 62,
          growthIndex: 61,
          pest: null,
        },
        {
          id: 2,
          simMin: startMin - 330,
          zoneId: "z3",
          zoneName: "Vertical wall A",
          moisture: 31,
          light: 48,
          growthIndex: 62,
          pest: {
            name: "Two-spotted mite",
            confidence: 0.74,
            status: "needs-review",
          },
        },
        {
          id: 3,
          simMin: startMin - 240,
          zoneId: "z2",
          zoneName: "Tomato bed",
          moisture: 37,
          light: 70,
          growthIndex: 64,
          pest: null,
        },
      ],
    },
    tasks: buildTasks(startMin),
    taskSeq: 6,
    notes: [
      {
        id: 1,
        simMin: startMin - 600,
        text: "Flowering started on the second truss — feeding twice a week from now.",
      },
      {
        id: 2,
        simMin: startMin - 200,
        text: "Top level of wall A dries first on windy afternoons; consider a second emitter line.",
      },
    ],
    noteSeq: 3,
    harvest: buildHarvest(),
    settings: {
      gardenName: "Terrace garden",
      location: "Delhi, IN",
      units: "metric",
      clock24h: true,
      respectQuietHours: true,
      quietStartMin: 22 * 60,
      quietEndMin: 6 * 60,
      notifyCritical: true,
      notifyWarn: true,
      dailyDigest: true,
      retentionDays: 365,
      offlineFallback: "local",
    },
    lastRainEndSimMin: null,
  };
}

// ---- small shared helpers ---------------------------------------------------
/** Daylight 0..1 at a simulated minute — the same curve the engine evaporates against. */
export function daylightAt(simMin: number) {
  return dayFactor(simMin);
}

function dayFactor(simMin: number) {
  // daylight 0..1: sunrise 05:40, peak 13:00, sunset 19:40
  const t = simMin % DAY_MIN;
  if (t < 340 || t > 1180) return 0;
  const x = (t - 340) / 840; // 0..1
  return Math.pow(Math.sin(Math.PI * x), 1.3);
}

/** How many events the demo keeps on disk — the Settings retention slider drives it. */
export function logCapFor(retentionDays: number) {
  return Math.round(clamp(Math.round(retentionDays * 0.6), 40, 600));
}

function pushLog(state: SimState, kind: AlertKind, source: string, message: string): SimState {
  const entry: LogEntry = {
    id: state.logSeq,
    simMin: state.simMin,
    realTime: Date.now(),
    kind,
    source,
    message,
  };
  const log = [entry, ...state.log].slice(0, logCapFor(state.settings.retentionDays));
  return { ...state, log, logSeq: state.logSeq + 1 };
}

function inQuietHours(state: SimState) {
  const s = state.settings;
  if (!s.respectQuietHours) return false;
  return minutesInWindow(state.simMin, s.quietStartMin, s.quietEndMin);
}

function pushAlert(state: SimState, kind: AlertKind, title: string, detail: string): SimState {
  if (state.alerts.some(a => a.title === title && state.simMin - a.simMin < 60 && !a.acked)) return state; // dedupe within 1h sim
  // Warnings obey the notification profile; critical safety alerts can never be muted.
  if (kind === "warn" && !state.settings.notifyWarn) {
    return pushLog(state, "warn", "Alerts", `Warning muted by notification settings — ${title.toLowerCase()}.`);
  }
  if (inQuietHours(state) && kind !== "critical") {
    return pushLog(state, kind, "Alerts", `Held during quiet hours — ${title.toLowerCase()}.`);
  }
  const alert: AlertEntry = {
    id: state.alertSeq,
    kind,
    title,
    detail,
    simMin: state.simMin,
    acked: false,
  };
  const alerts = [alert, ...state.alerts].slice(0, 40);
  return { ...state, alerts, alertSeq: state.alertSeq + 1 };
}

function minutesInWindow(simMin: number, startMin: number, endMin: number) {
  const t = ((simMin % DAY_MIN) + DAY_MIN) % DAY_MIN;
  if (startMin === endMin) return true;
  if (startMin < endMin) return t >= startMin && t < endMin;
  return t >= startMin || t < endMin; // window wrapping past midnight
}

export function autoWindowOpen(state: SimState) {
  const enabled = state.rules.windows.filter(w => w.enabled);
  if (enabled.length === 0) return true; // no windows armed — rules run all day
  return enabled.some(w => minutesInWindow(state.simMin, w.startMin, w.endMin));
}

const fmtClock = (simMin: number, clock24h = true) => {
  const t = ((simMin % DAY_MIN) + DAY_MIN) % DAY_MIN;
  const h24 = Math.floor(t / 60);
  const m = Math.floor(t % 60)
    .toString()
    .padStart(2, "0");
  if (clock24h) return `${h24.toString().padStart(2, "0")}:${m}`;
  const suffix = h24 < 12 ? "AM" : "PM";
  const h12 = h24 % 12 === 0 ? 12 : h24 % 12;
  return `${h12}:${m} ${suffix}`;
};

// Unit-aware formatters used by the demo pages so the Settings page is honest.
export function formatTemp(celsius: number, units: UnitSystem = "metric", digits = 1) {
  if (units === "imperial") return `${((celsius * 9) / 5 + 32).toFixed(digits)}°F`;
  return `${celsius.toFixed(digits)}°C`;
}

export function formatVolume(liters: number, units: UnitSystem = "metric", digits = 1) {
  if (units === "imperial") return `${(liters * 0.264172).toFixed(digits)} gal`;
  return `${liters.toFixed(digits)} L`;
}

export function formatDepth(mm: number, units: UnitSystem = "metric") {
  if (units === "imperial") return `${(mm / 25.4).toFixed(2)} in`;
  return `${mm.toFixed(1)} mm`;
}

// ---- the tick ---------------------------------------------------------------
export function simTick(prev: SimState): SimState {
  if (!prev.running) return prev;
  let state = {
    ...prev,
    simMin: prev.simMin + TICK_MIN,
    weather: { ...prev.weather },
    tank: { ...prev.tank },
    rules: { ...prev.rules, windows: prev.rules.windows.map(w => ({ ...w })) },
    harvest: { ...prev.harvest },
    camera: { ...prev.camera },
    fertilizer: {
      ...prev.fertilizer,
      channels: prev.fertilizer.channels.map(c => ({ ...c })),
    },
    devices: prev.devices.map(d => ({ ...d })),
  };

  // --- weather ---
  const day = dayFactor(state.simMin);
  const t = state.simMin % DAY_MIN;
  const heatBase = 16 + 11 * day;
  const noise = (rand() - 0.5) * 1.6;
  const temp = round1(clamp(heatBase + noise, 2, 40));
  const humidity = round1(clamp(92 - 26 * day - (temp - 16) * 1.4 + (rand() - 0.5) * 5, 22, 98));
  const light = round1(clamp(day * 100 + (rand() - 0.5) * 6, 0, 100));
  const wind = round1(clamp(3 + 9 * day + (rand() - 0.5) * 4, 0, 28));

  // rain events: higher chance in simulated late afternoon, with 2.5% base
  let raining = state.weather.raining;
  let rainIntensity = state.weather.rainIntensity;
  let rainMmPerHour = state.weather.rainMmPerHour;
  if (state.weather.raining) {
    rainIntensity = clamp(rainIntensity - rand() * 0.14, 0, 1);
    if (rainIntensity <= 0.02) {
      raining = false;
      rainIntensity = 0;
      rainMmPerHour = 0;
    } else {
      rainMmPerHour = round1(4 + rainIntensity * 22);
    }
  } else if (rand() < 0.016 + (t > 900 && t < 1140 ? 0.02 : 0)) {
    raining = true;
    rainIntensity = 0.35 + rand() * 0.6;
    rainMmPerHour = round1(4 + rainIntensity * 22);
  }

  state = {
    ...state,
    weather: {
      temp,
      humidity,
      light,
      wind,
      raining,
      rainIntensity: round1(rainIntensity),
      rainMmPerHour,
    },
  };

  const wasRaining = prev.weather.raining;
  if (wasRaining && !state.weather.raining) {
    state = { ...state, lastRainEndSimMin: state.simMin };
  }

  // --- rainwater harvesting: rain on the catchment fills the tank ---
  if (state.weather.raining) {
    const mm = (state.weather.rainMmPerHour / 60) * TICK_MIN; // 1 mm on 1 m² = 1 L
    const liters = round1(mm * state.harvest.catchmentM2 * state.harvest.efficiency);
    const harvest = {
      ...state.harvest,
      rainMmToday: round1(state.harvest.rainMmToday + mm),
      collectedTodayL: round1(state.harvest.collectedTodayL + liters),
      collectedTotalL: round1(state.harvest.collectedTotalL + liters),
    };
    harvest.daily = [...state.harvest.daily];
    harvest.daily[harvest.daily.length - 1] = {
      ...harvest.daily[harvest.daily.length - 1],
      mm: round1(harvest.daily[harvest.daily.length - 1].mm + mm),
      liters: round1(harvest.daily[harvest.daily.length - 1].liters + liters),
    };

    if (harvest.routedToTank && liters > 0) {
      const free = Math.max(0, state.tank.capacity - state.tank.level);
      const stored = round1(Math.min(free, liters));
      const spilled = round1(liters - stored);
      const tank = {
        ...state.tank,
        level: round1(clamp(state.tank.level + stored, 0, state.tank.capacity)),
        rainShare: round1(state.tank.rainShare + stored),
      };
      state = { ...state, tank, harvest };
      if (spilled > 0.2) {
        const lastIdx = harvest.daily.length - 1;
        state = {
          ...state,
          harvest: {
            ...state.harvest,
            overflowCount: state.harvest.overflowCount + 1,
            lastOverflowSimMin: state.simMin,
            daily: [...state.harvest.daily.slice(0, lastIdx), { ...state.harvest.daily[lastIdx], overflow: true }],
          },
        };
        state = pushLog(state, "warn", "Harvest", `Tank at capacity — ${formatVolume(spilled, "metric", 1)} of harvested rain diverted to overflow.`);
        state = pushAlert(state, "warn", "Rain harvest overflow", `Storage is full, so ${formatVolume(spilled, "metric", 1)} of rainfall went to the drain. Reduce the municipal inlet or add storage.`);
      }
    } else {
      state = { ...state, harvest };
    }
  }

  // --- devices: battery, radio, reboots, OTA, faults ---
  const backOnline: string[] = [];
  const devices = state.devices.map(device => {
    const next = {
      ...device,
      rssi: round1(clamp(device.rssi + (rand() - 0.5) * 2.4, -94, -38)),
    };

    if (!next.online && next.offlineUntilSimMin !== null && state.simMin >= next.offlineUntilSimMin) {
      next.online = true;
      next.offlineUntilSimMin = null;
      const updatedTo = next.pendingFirmware;
      next.pendingFirmware = null;
      if (updatedTo) next.firmware = updatedTo;
      backOnline.push(`${device.name} back online${updatedTo ? ` after installing v${updatedTo}` : ""}.`);
    }
    if (next.online) {
      next.lastSeenSimMin = state.simMin;
      // Kept un-rounded on purpose: a node leaks a fraction of a percent per tick, and snapping to
      // one decimal would round the whole drain away. About 0.5%/sim-hour, like real soil nodes.
      if (next.powered === "battery") {
        next.battery = clamp((next.battery ?? 100) - 0.035 - state.weather.light / 6000, 0, 100);
      } else if (next.powered === "solar") {
        const drain = 0.03 + state.weather.wind / 2000;
        const charge = day * 0.075 * (state.weather.light / 100) + day * 0.02;
        next.battery = clamp((next.battery ?? 100) - drain + charge, 0, 100);
      }
      if (next.battery !== null && next.battery < 15 && !next.fault) {
        next.fault = `Low battery (${next.battery.toFixed(0)}%) — reporting interval stretched`;
      }
    }
    return next;
  });
  state = { ...state, devices };
  for (const line of backOnline) state = pushLog(state, "ok", "Devices", line);

  const deviceById = new Map(devices.map(d => [d.id, d]));
  const controller = deviceById.get("edge-01");
  const controllerOnline = controller ? controller.online : true;
  // "local" fallback keeps the last validated thresholds running at the edge; "safe-stop" halts actuators.
  const haltForController = !controllerOnline && state.settings.offlineFallback === "safe-stop";

  const zones = state.zones.map(z => ({ ...z }));
  const logLines: { kind: AlertKind; source: string; message: string }[] = [];
  const newAlerts: { kind: AlertKind; title: string; detail: string }[] = [];

  const tank = state.tank;
  let flow = 0;
  let rainwaterUsed = 0;
  const fertChannels = state.fertilizer.channels.map(c => ({ ...c }));

  const rainHoldActive = state.rules.rainSkipMin > 0 && state.lastRainEndSimMin !== null && state.simMin - state.lastRainEndSimMin < state.rules.rainSkipMin;
  const windowOpen = autoWindowOpen(state);
  const freezeHold = temp <= state.rules.freezeProtectC;
  const tankCritical = tank.level <= tank.criticalThreshold;

  for (const zone of zones) {
    zone.temp = round1(clamp(temp + (rand() - 0.5) * 1.2, -6, 45));
    zone.light = light;

    const evap = (0.055 + 0.011 * day + Math.max(0, temp - 16) * 0.0035 + state.weather.wind / 2600) * TICK_MIN; // % moisture lost per tick
    zone.moisture = round1(clamp(zone.moisture - evap, 6, 100));

    // rain wets the zone
    if (state.weather.raining) {
      zone.moisture = round1(clamp(zone.moisture + state.weather.rainIntensity * 0.42 * TICK_MIN, 6, 100));
    }

    const tooDry = zone.moisture <= zone.target - 3;
    const sensorId = soilDeviceId(zone.id);
    const valveId = valveDeviceId(zone.id);
    const sensorOnline = deviceById.get(sensorId)?.online ?? true;
    const valveOnline = deviceById.get(valveId)?.online ?? true;

    // stop reasons evaluated for the running or a prospective cycle
    const holdReasons: string[] = [];
    if (!zone.auto) holdReasons.push("manual mode");
    if (!state.autoGlobal) holdReasons.push("auto off");
    if (state.emergencyStop) holdReasons.push("emergency stop");
    if (state.weather.raining) holdReasons.push("rain falling");
    else if (rainHoldActive) holdReasons.push("rain hold-over");
    if (!windowOpen) holdReasons.push("outside schedule");
    if (freezeHold) holdReasons.push("freeze protection");
    if (tankCritical) holdReasons.push("tank critical");
    if (!sensorOnline) holdReasons.push("sensor offline");
    if (haltForController) holdReasons.push("controller offline");
    if (!valveOnline) holdReasons.push("actuator offline");

    const wantWater = tooDry;
    zone.wantsWater = wantWater;
    zone.holdReason = wantWater && holdReasons.length > 0 ? holdReasons[0] : null;

    const stopBand = zone.target + (state.eco ? 1.5 : 3);

    if (zone.valveOpen) {
      const cycleAge = zone.cycleStartSimMin === null ? 0 : state.simMin - zone.cycleStartSimMin;
      const atCycleLimit = cycleAge >= state.rules.maxCycleMin;
      const mustClose = zone.moisture >= stopBand || state.emergencyStop || tankCritical || haltForController || !valveOnline;
      if (mustClose || atCycleLimit) {
        zone.valveOpen = false;
        zone.cycleStartSimMin = null;
        if (atCycleLimit && !mustClose) {
          logLines.push({
            kind: zone.moisture < zone.target - 3 ? "critical" : "warn",
            source: "Safety",
            message: `${zone.name}: cycle limit ${state.rules.maxCycleMin} min reached — valve closed${zone.moisture < zone.target - 3 ? " without reaching target" : ""}.`,
          });
          if (zone.moisture < zone.target - 3) {
            const dev = deviceById.get(valveId);
            if (dev && !dev.fault) {
              dev.fault = "Valve feedback mismatch — open with no moisture rise";
              newAlerts.push({
                kind: "critical",
                title: `Suspected stuck valve: ${zone.name}`,
                detail: `The cycle ran the full ${state.rules.maxCycleMin} min and soil moisture is still ${zone.moisture.toFixed(0)}%. Inspect the line before the next automatic cycle.`,
              });
            }
          }
        }
      } else {
        // continue the running cycle
        const rate = 1.35; // l per sim minute
        const draw = Math.min(rate * TICK_MIN, tank.level);
        zone.moisture = round1(clamp(zone.moisture + draw * 3.1, 6, 100));
        zone.consumedToday = round1(zone.consumedToday + draw);
        zone.consumedTotal = round1(zone.consumedTotal + draw);
        zone.lastWateredSimMin = state.simMin;
        flow += rate;

        const fromRain = Math.min(tank.rainShare, draw);
        tank.rainShare = round1(Math.max(0, tank.rainShare - fromRain));
        tank.muniShare = round1(Math.max(0, tank.muniShare - (draw - fromRain)));
        tank.level = round1(clamp(tank.level - draw, 0, tank.capacity));
        rainwaterUsed += fromRain;

        // fertilizer dosing rides the open line
        if (state.fertilizer.enabled && !state.fertilizer.lockout) {
          for (const channel of fertChannels) {
            if (channel.zoneId !== zone.id || !channel.enabled) continue;
            const dose = Math.min((channel.doseMl / 4) * (TICK_MIN / 4), channel.reservoirMl);
            if (dose <= 0) continue;
            channel.reservoirMl = round1(channel.reservoirMl - dose);
            channel.todayMl = round1(channel.todayMl + dose);
            channel.totalMl = round1(channel.totalMl + dose);
            channel.lastDosedSimMin = state.simMin;
            zone.fertApplied = round1(zone.fertApplied + dose);
          }
        }
      }
    }

    if (!zone.valveOpen) {
      zone.fertApplied = 0;
      if (wantWater && holdReasons.length === 0) {
        if (state.rules.dryRun) {
          logLines.push({
            kind: "info",
            source: "Dry run",
            message: `DRY RUN — ${zone.name}: would open valve at ${zone.moisture.toFixed(0)}% for target ${zone.target.toFixed(0)}%.`,
          });
        } else {
          zone.valveOpen = true;
          zone.cycleStartSimMin = state.simMin;
          logLines.push({
            kind: "info",
            source: "Irrigation",
            message: `${zone.name}: automatic cycle opened (moisture ${zone.moisture.toFixed(0)}%, target ${zone.target.toFixed(0)}%).`,
          });
        }
      }
    }

    zone.pausedByRain = Boolean(zone.auto && state.weather.raining && tooDry);
  }

  // persist device mutations (faults set above)
  state = {
    ...state,
    zones,
    tank,
    devices,
    fertilizer: { ...state.fertilizer, channels: fertChannels },
  };

  state = {
    ...state,
    waterToday: round1(state.waterToday + flow * TICK_MIN),
    rainwaterToday: round1(state.rainwaterToday + rainwaterUsed),
    estimatedSavingsL: round1(state.estimatedSavingsL + rainwaterUsed),
  };

  // --- alerts & log ---
  if (!wasRaining && state.weather.raining) {
    state = pushLog(state, "info", "Weather", `Rain started (${Math.round(state.weather.rainIntensity * 100)}% intensity, ~${state.weather.rainMmPerHour.toFixed(0)} mm/h) — automatic watering paused.`);
    state = pushAlert(state, "info", "Rain detected", "Automatic irrigation is paused while rain is falling. Rainwater collection is active.");
  }
  if (wasRaining && !state.weather.raining) {
    state = pushLog(state, "ok", "Weather", `Rain ended — automatic watering resumes after a ${state.rules.rainSkipMin} min hold-over.`);
  }

  for (const line of logLines) state = pushLog(state, line.kind, line.source, line.message);
  for (const alert of newAlerts) state = pushAlert(state, alert.kind, alert.title, alert.detail);

  if (freezeHold) {
    state = pushAlert(state, "warn", "Freeze protection", `Ambient temperature is ${formatTemp(temp, state.settings.units)} — at or below the ${formatTemp(state.rules.freezeProtectC, state.settings.units, 0)} guard. Irrigation is held.`);
  }
  if (!controllerOnline) {
    state = pushAlert(
      state,
      state.settings.offlineFallback === "safe-stop" ? "critical" : "warn",
      "Edge controller offline",
      state.settings.offlineFallback === "safe-stop"
        ? "Configured fallback is safe-stop: every valve is held closed until the controller reports back."
        : "Configured fallback is local-rules: the last validated thresholds keep protecting the garden without the cloud."
    );
  }

  const minMoisture = Math.min(...state.zones.map(z => z.moisture));
  const maxMoisture = Math.max(...state.zones.map(z => z.moisture));
  const dryZone = state.zones.find(z => z.moisture <= z.target - 8 && !z.valveOpen && !state.weather.raining && !state.emergencyStop);
  if (dryZone) {
    state = pushAlert(state, "warn", `Zone dry: ${dryZone.name}`, `Soil moisture ${dryZone.moisture.toFixed(0)}% is well below its ${dryZone.target.toFixed(0)}% target.`);
  }
  if (maxMoisture >= 88) {
    state = pushAlert(state, "warn", "High soil moisture", `A zone reached ${maxMoisture.toFixed(0)}% — verify drainage and valve state.`);
  }
  if (state.tank.level <= state.tank.criticalThreshold) {
    state = pushLog(state, "critical", "Tank", `Critical tank level: ${state.tank.level.toFixed(0)} L. Irrigation cut off.`);
    state = pushAlert(state, "critical", "Tank critical", `${state.tank.level.toFixed(0)} L remaining — all valves are cut off below ${state.tank.criticalThreshold} L.`);
  } else if (state.tank.level <= state.tank.lowThreshold && prev.tank.level > state.tank.lowThreshold) {
    state = pushLog(state, "warn", "Tank", `Low tank level: ${state.tank.level.toFixed(0)} L.`);
    state = pushAlert(state, "warn", "Tank running low", `${state.tank.level.toFixed(0)} L remaining. Consider topping up or checking the municipal inlet.`);
  }
  if (temp >= 34) {
    state = pushAlert(state, "critical", "Heat alert", `Ambient temperature reached ${formatTemp(temp, state.settings.units)}. Shade and evening watering recommended.`);
  }
  if (minMoisture < 18 && !state.emergencyStop) {
    state = pushAlert(state, "critical", "Plant stress risk", "A zone is critically dry. Enable watering or run a manual cycle.");
  }
  if (state.rules.dryRun) {
    state = pushAlert(state, "info", "Dry-run mode", "The engine is logging what it would do and is not driving any actuator. Turn dry-run off to let the rules run.");
  }

  // --- camera: interval capture, growth index, advisory pest signatures ---
  let camera = state.camera;
  if (camera.enabled && (deviceById.get("cam-01")?.online ?? true)) {
    const dueForCapture = camera.lastCaptureSimMin === null || state.simMin - camera.lastCaptureSimMin >= camera.intervalMin;
    const avgMoistureNow = state.zones.reduce((sum, z) => sum + z.moisture, 0) / Math.max(1, state.zones.length);
    const inBand = state.zones.filter(z => z.moisture >= z.target - 6 && z.moisture <= z.target + 14).length;
    const growthStep = inBand === state.zones.length ? 0.55 : inBand > 0 ? 0.22 : 0.04;
    camera = {
      ...camera,
      growthIndex: round1(clamp(camera.growthIndex + growthStep, 0, 100)),
    };
    if (dueForCapture) {
      const zone = state.zones[camera.captures % Math.max(1, state.zones.length)];
      const pestRoll = rand();
      const pest: PestSignature | null =
        pestRoll < 0.13
          ? {
              name: pestLibrary[Math.floor(rand() * pestLibrary.length)],
              confidence: Math.round((0.55 + rand() * 0.34) * 100) / 100,
              status: "needs-review",
            }
          : null;
      const snapshot: Snapshot = {
        id: camera.seq,
        simMin: state.simMin,
        zoneId: zone?.id ?? "z1",
        zoneName: zone?.name ?? "Garden",
        moisture: zone ? zone.moisture : avgMoistureNow,
        light,
        growthIndex: camera.growthIndex,
        pest,
      };
      camera = {
        ...camera,
        seq: camera.seq + 1,
        captures: camera.captures + 1,
        lastCaptureSimMin: state.simMin,
        storagePct: round1(clamp(camera.storagePct + 0.6, 0, 100)),
        snapshots: [snapshot, ...camera.snapshots].slice(0, 40),
      };
      if (pest) {
        state = pushLog(state, "warn", "Camera", `Advisory signature on ${zone?.name ?? "garden"}: ${pest.name} at ${(pest.confidence * 100).toFixed(0)}% confidence. Human review required.`);
        state = pushAlert(
          state,
          "warn",
          `Pest signature: ${pest.name}`,
          `The camera flagged ${pest.name.toLowerCase()} on ${zone?.name ?? "a zone"} at ${(pest.confidence * 100).toFixed(0)}% confidence. Advisory only — confirm or dismiss before acting.`
        );
        state = addTask(state, {
          title: `Hand-check ${zone?.name ?? "the garden"} for ${pest.name.toLowerCase()}`,
          detail: `Camera confidence ${(pest.confidence * 100).toFixed(0)}%. Inspect undersides of leaves before treating; organic options first.`,
          kind: "check",
          dueSimMin: state.simMin + 180,
          zoneId: zone?.id,
        });
      }
      if (camera.storagePct > 92) {
        state = pushAlert(state, "warn", "Camera storage nearly full", `${camera.storagePct.toFixed(0)}% used — export the time-lapse sequence or raise the retention window.`);
      }
    }
  }
  const inBandNow = state.zones.filter(z => z.moisture >= z.target - 8 && z.moisture <= z.target + 18).length;
  camera = {
    ...camera,
    healthScore: Math.round(clamp(52 + (inBandNow / Math.max(1, state.zones.length)) * 34 + (state.emergencyStop ? -18 : 0), 0, 100)),
  };
  state = { ...state, camera };

  // --- generated garden tasks ---
  if (state.tank.level <= state.tank.lowThreshold) {
    state = addTaskIfNew(state, {
      title: "Top up the storage tank",
      detail: `${state.tank.level.toFixed(0)} L left. Refill from rain or the municipal inlet before the next window.`,
      kind: "care",
      dueSimMin: state.simMin + 120,
    });
  }
  const criticallyDry = state.zones.find(z => z.moisture < 18 && !z.valveOpen);
  if (criticallyDry) {
    state = addTaskIfNew(state, {
      title: `Hand-water ${criticallyDry.name}`,
      detail: `Soil is at ${criticallyDry.moisture.toFixed(0)}% with the valve closed. Run a manual cycle or check why the rules held.`,
      kind: "care",
      dueSimMin: state.simMin + 60,
      zoneId: criticallyDry.id,
    });
  }
  if (state.fertilizer.lockout) {
    state = addTaskIfNew(state, {
      title: "Clear the fertilizer lockout",
      detail: "Dosing channels are locked out. Verify the stock lines, then release the lockout.",
      kind: "check",
      dueSimMin: state.simMin + 240,
    });
  }
  const dueTasks = state.tasks.filter(task => !task.done && task.dueSimMin <= state.simMin);
  if (dueTasks.length > 0 && prev.tasks.filter(task => !task.done && task.dueSimMin <= prev.simMin).length === 0) {
    state = pushLog(state, "info", "Assistant", `${dueTasks.length} garden ${dueTasks.length === 1 ? "task is" : "tasks are"} due — ${dueTasks[0].title.toLowerCase()}.`);
  }

  // --- history ---
  const avgMoisture = round1(state.zones.reduce((sum, z) => sum + z.moisture, 0) / Math.max(1, state.zones.length));
  const point: SimHistoryPoint = {
    t: state.simMin,
    temp,
    humidity,
    light,
    wind,
    rain: state.weather.rainMmPerHour,
    avgMoisture,
    tankLevel: state.tank.level,
    flowRate: round1(flow),
    growthIndex: camera.growthIndex,
  };
  const history = [...state.history, point].slice(-240);

  return { ...state, history };
}

// ---- task helpers -----------------------------------------------------------
type NewTask = {
  title: string;
  detail: string;
  kind: TaskKind;
  dueSimMin: number;
  zoneId?: string;
  auto?: boolean;
};

function addTask(state: SimState, task: NewTask): SimState {
  const id = `t${state.taskSeq}`;
  const next: SimState = {
    ...state,
    tasks: [
      ...state.tasks,
      {
        id,
        title: task.title,
        detail: task.detail,
        kind: task.kind,
        dueSimMin: task.dueSimMin,
        done: false,
        auto: task.auto ?? true,
        zoneId: task.zoneId,
      },
    ].slice(-40),
    taskSeq: state.taskSeq + 1,
  };
  return pushLog(next, "info", "Assistant", `New task: ${task.title}.`);
}

function addTaskIfNew(state: SimState, task: NewTask): SimState {
  if (state.tasks.some(existing => !existing.done && existing.title === task.title)) return state;
  return addTask(state, task);
}

// ---- user actions -----------------------------------------------------------
export function startZoneWatering(state: SimState, zoneId: string): SimState {
  const zones = state.zones.map(z =>
    z.id === zoneId
      ? {
          ...z,
          valveOpen: true,
          auto: false,
          lastWateredSimMin: state.simMin,
          cycleStartSimMin: state.simMin,
        }
      : z
  );
  let next: SimState = { ...state, zones, emergencyStop: false };
  next = pushLog(next, "info", "Irrigation", `${zones.find(z => z.id === zoneId)?.name ?? zoneId}: manual watering started${state.rules.dryRun ? " (dry-run — actuators held)" : ""}.`);
  return next;
}

export function stopZoneWatering(state: SimState, zoneId: string): SimState {
  const zones = state.zones.map(z => (z.id === zoneId ? { ...z, valveOpen: false, cycleStartSimMin: null } : z));
  let next: SimState = { ...state, zones };
  next = pushLog(next, "ok", "Irrigation", `${zones.find(z => z.id === zoneId)?.name ?? zoneId}: watering stopped.`);
  return next;
}

export function emergencyStop(state: SimState): SimState {
  const zones = state.zones.map(z => ({
    ...z,
    valveOpen: false,
    cycleStartSimMin: null,
  }));
  let next: SimState = { ...state, zones, emergencyStop: true };
  next = pushLog(next, "critical", "Safety", "EMERGENCY STOP — all pumps and valves halted. Local override engaged.");
  next = pushAlert(next, "critical", "Emergency stop engaged", "All actuators are off. Clear the stop to resume any automatic or manual irrigation.");
  return next;
}

export function clearEmergencyStop(state: SimState): SimState {
  let next: SimState = { ...state, emergencyStop: false };
  next = pushLog(next, "ok", "Safety", "Emergency stop cleared — normal control restored.");
  return next;
}

export function refillTank(state: SimState, liters: number, source: "rain" | "municipal"): SimState {
  const tank = state.tank;
  const amount = Math.min(liters, tank.capacity - tank.level);
  let next: SimState = {
    ...state,
    tank: {
      ...tank,
      level: round1(tank.level + amount),
      rainShare: round1(tank.rainShare + (source === "rain" ? amount : 0)),
      muniShare: round1(tank.muniShare + (source === "municipal" ? amount : 0)),
    },
  };
  next = pushLog(next, "info", "Tank", `Tank refilled +${formatVolume(amount, state.settings.units)} from ${source === "rain" ? "rainwater storage" : "municipal inlet"}.`);
  return next;
}

export function toggleEco(state: SimState): SimState {
  const eco = !state.eco;
  let next: SimState = { ...state, eco };
  next = pushLog(next, "info", "Rules", `Eco mode ${eco ? "enabled — rainwater-first, lean cycles" : "disabled — standard cycles"}.`);
  return next;
}

export function toggleAutoGlobal(state: SimState): SimState {
  const autoGlobal = !state.autoGlobal;
  let next: SimState = {
    ...state,
    autoGlobal,
    zones: state.zones.map(z => ({
      ...z,
      valveOpen: autoGlobal ? z.valveOpen : false,
      cycleStartSimMin: autoGlobal ? z.cycleStartSimMin : null,
    })),
  };
  next = pushLog(next, "info", "Rules", `Automatic irrigation ${autoGlobal ? "enabled" : "disabled"}.`);
  return next;
}

export function setZoneAuto(state: SimState, zoneId: string, auto: boolean): SimState {
  const zones = state.zones.map(z => (z.id === zoneId ? { ...z, auto, valveOpen: auto ? z.valveOpen : false } : z));
  let next: SimState = { ...state, zones };
  next = pushLog(next, "info", "Irrigation", `${zones.find(z => z.id === zoneId)?.name ?? zoneId}: automatic mode ${auto ? "enabled" : "switched to manual"}.`);
  return next;
}

export function setZoneTarget(state: SimState, zoneId: string, target: number): SimState {
  const zones = state.zones.map(z => (z.id === zoneId ? { ...z, target: round1(clamp(target, 20, 70)) } : z));
  let next: SimState = { ...state, zones };
  next = pushLog(next, "info", "Rules", `${zones.find(z => z.id === zoneId)?.name ?? zoneId}: moisture target set to ${target}%.`);
  return next;
}

export function setSimSpeed(state: SimState, speed: number): SimState {
  return { ...state, speed };
}

const extraZonePlants = ["Mint & basil", "Chillies", "Spinach", "Lettuce mix", "Coriander", "Microgreens", "Rosemary"];
const extraZoneNames = ["New raised bed", "Window box", "Vertical wall C", "Herb rail", "Corner planter", "Greenhouse shelf"];
let zoneSeq = zoneDefaults.length + 1;

export function addZone(state: SimState): SimState {
  const id = `z${zoneSeq++}`;
  const name = extraZoneNames[(zoneSeq - 5) % extraZoneNames.length];
  const plant = extraZonePlants[Math.floor(rand() * extraZonePlants.length)];
  const zone: ZoneState = {
    id,
    name,
    plant,
    moisture: round1(28 + rand() * 20),
    target: round1(32 + rand() * 12),
    temp: state.weather.temp,
    light: state.weather.light,
    valveOpen: false,
    auto: true,
    pausedByRain: false,
    lastWateredSimMin: null,
    consumedToday: 0,
    consumedTotal: round1(rand() * 20),
    cycleStartSimMin: null,
    wantsWater: false,
    holdReason: null,
    fertApplied: 0,
  };
  const devices: DeviceState[] = [
    ...state.devices,
    {
      id: soilDeviceId(id),
      name: `${name} — soil node`,
      kind: "sensor",
      model: "Capacitive soil · DS18B20 soil temp",
      zoneId: id,
      powered: "battery",
      battery: 98,
      rssi: -64,
      firmware: "1.2.0",
      pendingFirmware: null,
      online: true,
      offlineUntilSimMin: null,
      lastSeenSimMin: state.simMin,
      fault: null,
    },
    {
      id: valveDeviceId(id),
      name: `${name} — valve`,
      kind: "valve",
      model: "Normally-closed solenoid · 24 V",
      zoneId: id,
      powered: "mains",
      battery: null,
      rssi: -63,
      firmware: "1.1.8",
      pendingFirmware: null,
      online: true,
      offlineUntilSimMin: null,
      lastSeenSimMin: state.simMin,
      fault: null,
    },
  ];
  let next: SimState = { ...state, zones: [...state.zones, zone], devices };
  next = pushLog(next, "info", "Zones", `Zone added: ${name} (${plant}). Soil node and valve provisioned and paired.`);
  return next;
}

export function removeZone(state: SimState, zoneId: string): SimState {
  if (state.zones.length <= 1) return state;
  const zone = state.zones.find(z => z.id === zoneId);
  const zones = state.zones.filter(z => z.id !== zoneId);
  const devices = state.devices.filter(d => d.zoneId !== zoneId);
  const channels = state.fertilizer.channels.filter(c => c.zoneId !== zoneId);
  let next: SimState = {
    ...state,
    zones,
    devices,
    fertilizer: { ...state.fertilizer, channels },
  };
  next = pushLog(next, "warn", "Zones", `${zone?.name ?? "Zone"} removed from the loop.`);
  return next;
}

// --- rules & schedules ---
export function patchRules(state: SimState, patch: Partial<Omit<RulesState, "windows">>, logMessage?: string): SimState {
  let next: SimState = { ...state, rules: { ...state.rules, ...patch } };
  if (logMessage) next = pushLog(next, "info", "Rules", logMessage);
  return next;
}

export function toggleScheduleWindow(state: SimState, windowId: string): SimState {
  const windows = state.rules.windows.map(w => (w.id === windowId ? { ...w, enabled: !w.enabled } : w));
  const changed = windows.find(w => w.id === windowId);
  let next: SimState = { ...state, rules: { ...state.rules, windows } };
  next = pushLog(next, "info", "Rules", `Schedule window "${changed?.label ?? windowId}" ${changed?.enabled ? "armed" : "disarmed"}.`);
  return next;
}

export function setScheduleWindowTime(state: SimState, windowId: string, key: "startMin" | "endMin", minutes: number): SimState {
  const windows = state.rules.windows.map(w => (w.id === windowId ? { ...w, [key]: Math.round(clamp(minutes, 0, DAY_MIN - 1)) } : w));
  const changed = windows.find(w => w.id === windowId);
  let next: SimState = { ...state, rules: { ...state.rules, windows } };
  if (changed) {
    const label = key === "startMin" ? "opens" : "closes";
    next = pushLog(next, "info", "Rules", `${changed.label} ${label} at ${fmtClock(changed[key], state.settings.clock24h)}.`);
  }
  return next;
}

export function toggleDryRun(state: SimState): SimState {
  const dryRun = !state.rules.dryRun;
  let next: SimState = { ...state, rules: { ...state.rules, dryRun } };
  next = pushLog(next, dryRun ? "warn" : "ok", "Rules", dryRun ? "Dry-run mode ON — decisions are logged, no valve or pump will move." : "Dry-run mode OFF — validated decisions now drive the actuators.");
  if (dryRun) next = pushAlert(next, "info", "Dry-run mode", "The engine is previewing decisions only. Turn dry-run off to hand the garden back to the rules.");
  return next;
}

// --- devices ---
export function toggleDeviceOnline(state: SimState, deviceId: string): SimState {
  const devices = state.devices.map(d => (d.id === deviceId ? { ...d, online: !d.online, offlineUntilSimMin: null } : d));
  const device = devices.find(d => d.id === deviceId);
  let next: SimState = { ...state, devices };
  next = pushLog(next, device?.online ? "ok" : "warn", "Devices", `${device?.name ?? deviceId} manually set ${device?.online ? "online" : "offline"}.`);
  return next;
}

export function rebootDevice(state: SimState, deviceId: string): SimState {
  const devices = state.devices.map(d => (d.id === deviceId ? { ...d, online: false, offlineUntilSimMin: state.simMin + 20 } : d));
  const device = state.devices.find(d => d.id === deviceId);
  let next: SimState = { ...state, devices };
  next = pushLog(next, "info", "Devices", `${device?.name ?? deviceId}: reboot requested — back online in ~20 sim-min.`);
  return next;
}

/** Demo affordance: fast-forward a node's power budget so the low-battery path is reachable. */
export function drainDeviceBattery(state: SimState, deviceId: string, simHours = 24): SimState {
  const device = state.devices.find(d => d.id === deviceId);
  if (!device || device.battery === null) return state;
  const used = Math.min(device.battery, simHours * 0.5);
  const devices = state.devices.map(d => (d.id === deviceId ? { ...d, battery: clamp((d.battery ?? 100) - used, 0, 100) } : d));
  const drained = devices.find(d => d.id === deviceId);
  let next: SimState = { ...state, devices };
  next = pushLog(next, drained && drained.battery !== null && drained.battery < 15 ? "warn" : "info", "Devices", `${device.name}: power budget advanced ${simHours}h — battery now ${drained?.battery?.toFixed(0)}%.`);
  if (drained && drained.battery !== null && drained.battery < 15) {
    next = pushAlert(next, "warn", `Low battery: ${device.name}`, `${drained.battery.toFixed(0)}% remaining. The node stretches its reporting interval; swap or charge it before autonomy degrades.`);
    next = { ...next, devices: next.devices.map(d => (d.id === deviceId && !d.fault ? { ...d, fault: `Low battery (${d.battery?.toFixed(0)}%) — reporting interval stretched` } : d)) };
  }
  return next;
}

export function updateFirmware(state: SimState, deviceId: string): SimState {
  const devices = state.devices.map(d =>
    d.id === deviceId
      ? {
          ...d,
          online: false,
          offlineUntilSimMin: state.simMin + 45,
          pendingFirmware: d.pendingFirmware,
        }
      : d
  );
  const device = state.devices.find(d => d.id === deviceId);
  let next: SimState = { ...state, devices };
  next = pushLog(next, "info", "Devices", `${device?.name ?? deviceId}: OTA ${device?.pendingFirmware ?? "update"} queued — installing offline, zone control stays local.`);
  return next;
}

export function clearDeviceFault(state: SimState, deviceId: string): SimState {
  const devices = state.devices.map(d => (d.id === deviceId ? { ...d, fault: null } : d));
  const device = state.devices.find(d => d.id === deviceId);
  let next: SimState = { ...state, devices };
  next = pushLog(next, "ok", "Devices", `${device?.name ?? deviceId}: fault cleared by operator.`);
  return next;
}

// --- alerts ---
export function acknowledgeAlert(state: SimState, alertId: number): SimState {
  const alerts = state.alerts.map(a => (a.id === alertId ? { ...a, acked: true } : a));
  const alert = state.alerts.find(a => a.id === alertId);
  let next: SimState = { ...state, alerts };
  next = pushLog(next, "ok", "Alerts", `Acknowledged: ${alert?.title ?? "alert"}.`);
  return next;
}

export function acknowledgeAllAlerts(state: SimState): SimState {
  const open = state.alerts.filter(a => !a.acked).length;
  if (open === 0) return state;
  let next: SimState = {
    ...state,
    alerts: state.alerts.map(a => ({ ...a, acked: true })),
  };
  next = pushLog(next, "ok", "Alerts", `${open} ${open === 1 ? "alert" : "alerts"} acknowledged.`);
  return next;
}

// --- fertilizer ---
export function patchFertilizer(state: SimState, patch: Partial<Pick<FertilizerState, "enabled" | "lockout">>, logMessage: string): SimState {
  let next: SimState = {
    ...state,
    fertilizer: { ...state.fertilizer, ...patch },
  };
  return pushLog(next, "info", "Fertilizer", logMessage);
}

export function patchFertChannel(state: SimState, channelId: string, patch: Partial<Pick<FertChannel, "enabled" | "doseMl" | "reservoirMl">>, logMessage?: string): SimState {
  const channels = state.fertilizer.channels.map(c => (c.id === channelId ? { ...c, ...patch } : c));
  let next: SimState = {
    ...state,
    fertilizer: { ...state.fertilizer, channels },
  };
  if (logMessage) next = pushLog(next, "info", "Fertilizer", logMessage);
  return next;
}

export function doseChannelNow(state: SimState, channelId: string): SimState {
  const channel = state.fertilizer.channels.find(c => c.id === channelId);
  if (!channel) return state;
  if (state.fertilizer.lockout) {
    return pushLog(state, "critical", "Fertilizer", `Dose on ${channel.name} refused — safety lockout is engaged.`);
  }
  if (!state.fertilizer.enabled || !channel.enabled) {
    return pushLog(state, "warn", "Fertilizer", `Dose on ${channel.name} refused — the channel or the injector is off.`);
  }
  const amount = Math.min(channel.doseMl, channel.reservoirMl);
  if (amount <= 0) return pushLog(state, "warn", "Fertilizer", `${channel.name}: reservoir empty — refill before dosing.`);
  const channels = state.fertilizer.channels.map(c =>
    c.id === channelId
      ? {
          ...c,
          reservoirMl: round1(c.reservoirMl - amount),
          todayMl: round1(c.todayMl + amount),
          totalMl: round1(c.totalMl + amount),
          lastDosedSimMin: state.simMin,
        }
      : c
  );
  let next: SimState = {
    ...state,
    fertilizer: { ...state.fertilizer, channels },
  };
  next = pushLog(next, "info", "Fertilizer", `${channel.name}: manual dose ${amount.toFixed(0)} ml injected${channel.zoneId ? ` on ${state.zones.find(z => z.id === channel.zoneId)?.name ?? channel.zoneId}` : ""}.`);
  return next;
}

// --- camera ---
export function patchCamera(state: SimState, patch: Partial<Pick<CameraState, "enabled" | "intervalMin" | "storagePct">>, logMessage: string): SimState {
  let next: SimState = { ...state, camera: { ...state.camera, ...patch } };
  return pushLog(next, "info", "Camera", logMessage);
}

export function captureNow(state: SimState): SimState {
  if (!state.camera.enabled) return pushLog(state, "warn", "Camera", "Capture refused — the camera is disabled in settings.");
  if (state.camera.storagePct > 98) return pushLog(state, "warn", "Camera", "Capture refused — storage full. Export or purge the sequence.");
  const zone = state.zones[state.camera.captures % Math.max(1, state.zones.length)];
  const snapshot: Snapshot = {
    id: state.camera.seq,
    simMin: state.simMin,
    zoneId: zone?.id ?? "z1",
    zoneName: zone?.name ?? "Garden",
    moisture: zone?.moisture ?? 40,
    light: state.weather.light,
    growthIndex: state.camera.growthIndex,
    pest: null,
  };
  let next: SimState = {
    ...state,
    camera: {
      ...state.camera,
      seq: state.camera.seq + 1,
      captures: state.camera.captures + 1,
      lastCaptureSimMin: state.simMin,
      storagePct: round1(clamp(state.camera.storagePct + 0.6, 0, 100)),
      snapshots: [snapshot, ...state.camera.snapshots].slice(0, 40),
    },
  };
  next = pushLog(next, "info", "Camera", `Manual capture — ${snapshot.zoneName}, ${snapshot.moisture.toFixed(0)}% soil.`);
  return next;
}

export function reviewSnapshot(state: SimState, snapshotId: number, verdict: "confirmed" | "dismissed"): SimState {
  const snapshots = state.camera.snapshots.map(s => (s.id === snapshotId && s.pest ? { ...s, pest: { ...s.pest, status: verdict } } : s));
  const snapshot = state.camera.snapshots.find(s => s.id === snapshotId);
  let next: SimState = { ...state, camera: { ...state.camera, snapshots } };
  next = pushLog(next, verdict === "confirmed" ? "warn" : "ok", "Camera", `${snapshot?.zoneName ?? "Snapshot"}: ${snapshot?.pest?.name ?? "signature"} ${verdict} by human review.`);
  if (verdict === "confirmed") {
    next = addTaskIfNew(next, {
      title: `Treat ${snapshot?.zoneName ?? "the bed"} for ${snapshot?.pest?.name.toLowerCase() ?? "pest"}`,
      detail: "Confirmed from the camera review. Start with water blast and insecticidal soap; re-shoot in 48h.",
      kind: "care",
      dueSimMin: state.simMin + 240,
      zoneId: snapshot?.zoneId,
    });
  }
  return next;
}

// --- tasks & notes ---
export function completeTask(state: SimState, taskId: string): SimState {
  const task = state.tasks.find(t => t.id === taskId);
  const tasks = state.tasks.map(t => (t.id === taskId ? { ...t, done: !t.done } : t));
  let next: SimState = { ...state, tasks };
  next = pushLog(next, "ok", "Assistant", `${task?.done ? "Reopened" : "Completed"}: ${task?.title ?? taskId}.`);
  return next;
}

export function snoozeTask(state: SimState, taskId: string, minutes: number): SimState {
  const task = state.tasks.find(t => t.id === taskId);
  const tasks = state.tasks.map(t => (t.id === taskId ? { ...t, dueSimMin: state.simMin + minutes } : t));
  let next: SimState = { ...state, tasks };
  next = pushLog(next, "info", "Assistant", `${task?.title ?? "Task"} pushed ${minutes} sim-min.`);
  return next;
}

export function addGardenTask(state: SimState, title: string, kind: TaskKind = "note"): SimState {
  const clean = title.trim();
  if (!clean) return state;
  let next = addTask(state, {
    title: clean.slice(0, 90),
    detail: "Added by the gardener from the demo task list.",
    kind,
    dueSimMin: state.simMin + 240,
    auto: false,
  });
  return next;
}

export function addGardenNote(state: SimState, text: string): SimState {
  const clean = text.trim();
  if (!clean) return state;
  const note: GardenNote = {
    id: state.noteSeq,
    simMin: state.simMin,
    text: clean.slice(0, 240),
  };
  let next: SimState = {
    ...state,
    notes: [note, ...state.notes].slice(0, 40),
    noteSeq: state.noteSeq + 1,
  };
  next = pushLog(next, "info", "Assistant", `Note recorded: ${note.text.slice(0, 48)}${note.text.length > 48 ? "…" : ""}`);
  return next;
}

// --- harvest ---
export function patchHarvest(state: SimState, patch: Partial<Pick<HarvestState, "catchmentM2" | "efficiency" | "routedToTank">>, logMessage: string): SimState {
  let next: SimState = { ...state, harvest: { ...state.harvest, ...patch } };
  return pushLog(next, "info", "Harvest", logMessage);
}

// --- settings ---
export function patchSettings(state: SimState, patch: Partial<SiteSettings>): SimState {
  const settings = { ...state.settings, ...patch };
  let next: SimState = { ...state, settings };
  const key = Object.keys(patch)[0];
  if (key) {
    const value = patch[key as keyof SiteSettings];
    next = pushLog(next, "info", "Settings", `${key.replace(/([A-Z])/g, " $1").toLowerCase()} set to ${String(value)}.`);
  }
  return next;
}

export function pauseSim(state: SimState): SimState {
  let next: SimState = { ...state, running: false };
  next = pushLog(next, "info", "Demo", "Simulation paused.");
  return next;
}

export function resumeSim(state: SimState): SimState {
  let next: SimState = { ...state, running: true };
  next = pushLog(next, "info", "Demo", "Simulation resumed.");
  return next;
}

export function resetSim(): SimState {
  let state = initialSimState();
  state = pushLog(state, "info", "Demo", "Demo reset to a fresh garden state.");
  return state;
}

export const simClock = (simMin: number) => fmtClock(simMin);
export const minutesToTimeInput = (minutes: number) =>
  `${Math.floor(minutes / 60)
    .toString()
    .padStart(2, "0")}:${Math.floor(minutes % 60)
    .toString()
    .padStart(2, "0")}`;
export const timeInputToMinutes = (value: string) => {
  const [h, m] = value.split(":").map(part => Number(part));
  return (Number.isFinite(h) ? h : 0) * 60 + (Number.isFinite(m) ? m : 0);
};
export const simDay = (simMin: number) => Math.floor(simMin / DAY_MIN) + 1;
export { fmtClock as formatSimClock };
